set(SDL2_MIXER_INCLUDE_DIRS "${CMAKE_CURRENT_LIST_DIR}/SDL2_mixer/include")



if (${CMAKE_SIZEOF_VOID_P} MATCHES 8)
	set(SDL2_MIXER_LIBRARIES ${CMAKE_CURRENT_LIST_DIR}/SDL2_mixer/lib/x64/SDL2_mixer.lib)
	file(GLOB SDL2_mixer_DLL ${CMAKE_CURRENT_LIST_DIR}/SDL2_mixer/lib/x64/*.dll)
else ()
	set(SDL2_MIXER_LIBRARIES ${CMAKE_CURRENT_LIST_DIR}/SDL2_mixer/lib/x86/SDL2_mixer.lib)
	file(GLOB SDL2_mixer_DLL ${CMAKE_CURRENT_LIST_DIR}/SDL2_mixer/lib/x86/*.dll)
endif ()

string(STRIP "${SDL2_MIXER_LIBRARIES}" SDL2_MIXER_LIBRARIES)